* GNU Privacy Guard (GPG)
:PROPERTIES:
:CUSTOM_ID: gnu-privacy-guard-gpg
:END:
This is a free open source implementation of Phil Zimmermann's *Pretty
Good Privacy*, which he created back in 1991. You can use either one of
them to either encrypt or cryptographically sign files or messages. In
this section, we'll focus strictly on GPG.

There are some *advantages* of using GPG:

- It uses strong, hard-to-crack *encryption* algorithms.\\
- It uses the private/public key scheme, which eliminates the need to
  transfer a password to a message or file recipient in a secure manner.
  Instead, just send along your public key, which is useless to anyone
  other than the intended recipient.\\
- You can use GPG to just encrypt your own files for your own use, the
  same as you'd use any other encryption utility.\\
- It can be used to encrypt email messages, allowing you to have true
  end-to-end encryption for sensitive emails.\\
- There are a few GUI-type frontends available to make it somewhat
  easier to use.

But, as you might know, there are also some *disadvantages*:

- Using public keys instead of passwords is great when you work directly
  only with people who you implicitly trust. But for anything beyond
  that, such as distributing a public key to the general population so
  that everyone can verify your signed messages, you're dependent upon a
  web-of-trust model that can be very hard to set up.\\
- For the end-to-end encryption of email, the recipients of your email
  must also have GPG set up on their systems and know how to use it.
  That might work in a corporate environment, but lots of luck getting
  your friends to set that up. (I've never once succeeded in getting
  someone else to set up email encryption.)\\
- If you use a standalone email client, such as Mozilla Thunderbird, you
  can install a plugin that will encrypt and decrypt messages
  automatically. But every time a new Thunderbird update is released,
  the plugin breaks, and it always takes a while before a new working
  version gets released.\\
- Even if you could get other people to set up their email clients with
  GPG, it's still *not* the perfect privacy solution. That's because the
  email metadata---the email addresses of the sender and the
  recipient---can't be encrypted. So, hackers, advertisers, or
  government agencies can still see who you're exchanging email messages
  with, and use that information to build a profile that tells them a
  lot about your activities, your beliefs, and what kind of a person you
  are.

If you really need complete privacy, your best bet is to go with a
private messenger solution, such as the Session messenger. Even with its
numerous weaknesses, GPG is still one of the *best ways to share
encrypted files and emails*. GPG comes preinstalled on most Linux
distros.

Related: [[OpenSSL and Let's Encrypt]], [[Discretionary Access
Control]], [[SELinux]]
