#+title: RPM Query

*RPM* is used to /install/ local software packages. Once a package is installed the RPM package database is /updated/ with the software information. We can *query* that package database. We can also query a package directly even if it isn't installed. In addition, we can query a file. In reality, it's looking through the package database for a reference to the file. This only works for files that belong to software packages.

The ~-q~ option tells RPM to query, and ~-a~ means *all packages*.
Because we haven't specified a package or a file to query, RPM will query the database. You can query and pipe it into sort by using the command ~rpm -qa | sort~, therefore obtaining an alphabetical list.

- ~rpm -qi {package}~ to query installed information along with package version and short description
- ~rpm -qf~ to find out what package a file belongs to
- ~rpm -qcf {/path/to/file}~ to query a list of configuration files for a command
- ~rpm -qa~ --last to display all recently installed RPMs
- ~rpm -qpR {.rpm-file}~ or ~rpm -qR {package}~ to find out what dependencies a rpm file has

Other useful commands:
rpm -qa Group="System Environment/Shells" filter by group
rpm -ql yum
rpm -qc yum
rpm -qdf /bin/bash this shows all the doc for the specified command
rpm --provide (what does the package provides)
if we want to see what it requires rpm -q --requires
rpm -q --changelog
rpm -qip
rpm -qlp
