#+title: Quick Union Improvements

* Improvement 1: weighting
- Modify quick-union to avoid tall trees.
- Keep track of size of each tree.
- Balance by linking root of smaller tree to root of larger tree.

** Java implementation with weighting

- Data structure: same as quick-union, but mantain extra array sz[i] to count number of objects in the tree rooted at i;
- Find: identical to quick-union;
- Union: modify quick-union to
  - Link root of smaller tree to root of larger tree;
  - Update the sz[] array;

    #+begin_src java
    int i = root(p);
    int j = root(q);
    if (i==j) return;
    if (sz[i] < sz[j]) { id[i] = j; sz[j] += sz[i]; }
    else               { id[j] = i; sz[i] += sz[j]; }
    #+end_src

** Analysis

- Running time:
  - Find: takes time proportional to depth of p and q;
  - Union: takes constant time, given roots.

- Proposition
  - Depth of any node ~x~ is at most ~lg N~.
  - Proof
    When does depth of x increase?
    Increases by 1 when tree $T_1$ containing x is merged into another tree $T_2$.
    - The size of the tree contaiing ~x~ at least doubles since $| T_2 | >=| T_1 |$.
    - Size of tree containing ~x~ can double at most ~lg N~ times.

* Improvement 2: path compression

Quick union with path compression. Just after computing the root of ~p~, set the ~id~ of each examined node to point to that root.
** Java implementation
Just make every other node in path point to its grandparent, by simply adding:

~id[i] = id[id[i]]~

* Last cost analysis

quick find
- M N
quick union
- M N
weighted QU
- N + M log N
QU + path compression
- N + M log N
weighted QU + path compression
- N + M log N
