* Defmacro

Technically, a macro is a function that takes an s-expression as arguments and returns a LISP form, which is then evaluated.

Defmacro name lambda-list [[declaration* | documentation]] form*
Defines name as a macro by associating a macro function with that name in the global environment. The macro function is defined in the same lexical environment in which the defmacro form appears.

The expansion function accepts two arguments, a form and an environment. The expansion function returns a form. The body of the expansion function is specified by forms. Forms are executed in order. The value of the last form executed is returned as the expansion of the macro. The body forms of the expansion function (but not the lambda-list) are implicitly enclosed in a block whose name is name.

Defmacro can be used to redefine a macro or to replace a function definition with a macro definition. The basic skeleton of a DEFMACRO is quite similar to the skeleton of a DEFUN.

** Examples

#+begin_src lisp :tangle yes
(defmacro mac1 (a b) "Mac1 multiplies and adds"
            `(+ ,a (* ,b 3))) =>  MAC1
#+end_src
