* Gensym

Gensym creates unique symbols. Each call creates a new symbol. The symbol usually has a name which includes a number, which is counted up. The name is also unique (the symbol itself is already unique) with a number, so that a human reader can identify different uninterned symbols in the source code.

Gensym is often used in Lisp macros for code generation, when the macro needs to create new identifiers, which then don't clash with existing identifiers.

#+begin_src lisp :tangle yes
gensym &optional x => new-symbol
#+end_src

*** Arguments and Values:
x---a string or a non-negative integer.

Creates and returns a fresh, uninterned symbol, as if by calling make-symbol. (The only difference between gensym and make-symbol is in how the new-symbol's name is determined.)

The name of the new-symbol is the concatenation of a prefix, which defaults to "G", and a suffix, which is the decimal representation of a number that defaults to the value of *gensym-counter*.

*** Examples

#+begin_src lisp :tangle yes
(setq sym1 (gensym)) =>  #:G3142
(symbol-package sym1) =>  NIL
(setq sym2 (gensym 100)) =>  #:G100
#+end_src
