#+title: Examples of Proof by Contradiction and Induction

* Proof by Contradiction

To prove proposition $P$ is true, you will assume that is false, which means that $!P$ is false.
Then you use that hypothesis to derive a falsehood. (deriving a contradiction).Let's prove that $\sqrt(2)$ is irrational. 

Assuming for the purpose of contradiction that $\sqrt(2)$ is rational.

$$\sqrt(2)=a/b$$

$$\sqrt(2) = \frac{a^2}{b^2}$$

$$2b^2=a^2$$

$$(2|a)$$

$$4|a^2$
$$

$$4|2b^2$$

$$2|b^2$$

b is even => $a/b$ is not in lowest terms => contradiction

$\sqrt(2)$ is irrational

* Proof by Induction

** Introduction axiom

Let $P(m)$ be a predicate. If p(0) is true, and $\forall n \in N$ ==> $(P(n) => (P(n+1)))$ is true, then $\forall n \in N$. If $P(0), P(0) => P(1), P(1) => P(2)$ ... then $P(0), P(1), P(2)$ are true.

Let's prove that: 

$$\forall n \ge 0$$ 

$$1+2+3+...+n=\frac{n(n+1)}{2}$$

If $n=1$   ,   $1+2+...+n=1$ (we're summing the numbers from 1 to 1, which makes this expression quite ambigous).

If $n=0$   ,   $1+2+...+n=0$ (no integers to sum).

If $n=4$   ,   $1+2+...+n=10=\frac{4(5)}{2}$.

** Proof By induction

Let P(n) be proposition that \[\sum_{i=1}^{n}}=\frac{n(n+1)}{2}\]

** Base case

We have to check that P(0) is true
         $\sum_{i=1}^{0 = 0=\frac{0(0+1)}{2}$

** Inductive Step
We have to show that for $n \ge 0$ $P(n)=>P(n+i)$ is true.
Assume $P(n)$ is true (for purposes of induction).
Let's assume, $1+2+...+n = \frac{n(n+1)}{2}$.
We need to show that $1+2+...+(n+1)= \frac{(n+1)(n+2)}{2}$.

$$1+2...+n+(n+1)$$

$$\frac{n(n+1)}{2} + n+ 1 = \frac{n^2+n+2n+2}{2}=\frac{(n+1)(n+2)}{2}$$


* Theorem

$$\forall n \in N  3|(n^3-1)$$

$$(Ex. \ n=5 ,\ 3|(125-5)$$

** Proof By Induction

Let $P(n)$\ be \$3|(n^3-n)$

** Base case

$n = 0$   $3|(0-0)$

** Inductive Step

For n \ge 0, show P(n) => P(n+1) it true.
We assume that P(n) is true. In other words we assume that 3|(n^3-n)

Examine:

$$(n+1)^3-(n+1)$$

$$=n^3+3n^2+3n+1-(n+1)$$

$$= n^3+3n^2n$$

$$=n^3-n+3n^2+3n$$

$3|3n^3$

$3|3n$

$3|(n^3-n)$ by $P(n)$.

Which means $3|(n+1)^2-(n-1)$.

* False proof using induction
** Thm (not!) All horses are the same color.

** Proof by Induction

$P(n)$: in any set of n horses $(n \ge 1)$ the horses are all the same color.

** Base case

$n=1$ that would say that any set of one horses, the horses in the set all are  the same color.

$P(1)$ is true since just $1$ horse.

** Inductive Step

Assume that $P(n)$ is true to prove $P(n+1)$. Consider a set of $n+1$ horses and let's call these horses $H_1$ $H_2$ $H_{n+1}$

Then $H_1$, $H_2$,...$H_4$ are the same color. Also, $H_2, H_3$ and $H_{n+1}$  ''  ''  '' Since the color of $H_1$ equals the color of $ H_2 , H_n $ = the color of $ H_{n+1} $. That means that $H_1$ same color $H_n+1$ and all $H_n+1$ are the same color. The flaw consists on the ... notation.

$P(1)$    $P(2) => P(3)$, $P(3) => P(4)$

We did not prove that $P(1) => P(2)$
