#+title: Graph
#+author: Panariti Angelo
#+date: 31/05/2023

* Graph

A graph $G$ is a pair of sets often called $V$ and $E$, where $V$ is a set of elements called *vertices* or *nodes*, and $E$ is a set of 2 items subset of $V$ called edges.

* Adjacency

Two nodes $x_i$ and $x_j$ are *adjacent* if they're connected by an edge $(if\ x_i,x_j) \in E$.

* Incidence

An edge $E={x_i,x_j}$ is said to be *incident* to its end points $x_i, x_j$.

* Degree of a node

The number of edges incident to a node is called the degree of the node.

* Simple graph

A graph is simple if it has no loops or multiple edges.

* Example: Promiscuity Rate Based on Gender

$A_m=$ average number of opposite gender partners for men;

$A_w=$ average number of opposite gender partners for women;

$$\frac{A_m}{A_w}=1.74, 3.33$$

$$A_m=\frac{|E|}{|V_m|}$$

$$A_w=\frac{|E|}{|V_w|}$$

$$\frac{A_m}{A_w}=\frac{|E|/|V_m|}{|E|/|V_w|}=\frac{V_m}{V_w}=1.0325$$

* Bipartite Graphs

A graph $G$ is said to be *bipartite* if $V$ can be split into two sets $V_L$, $V_R$ so that all the edges connect a node in the left set to a node in the right set.
