#+title: Matching Problems
#+author: Panariti Angelo
#+date: 13/06/2023

** Definitions

Given graph $G=(V,E)$, a matching is a subgraph of $G$ where every node has degree 1.

A matching is perfect if it has size $\frac{|V|}{2}$.

The weight of a matching $M$ is the sum of the weights on the edges of $M$.

A min-weight matching for a graph $G$ is a perfect matching for $G$ with the min-weight.

Given a matching $M, x \notin y$ form a *rogue couple* if they prefer each other to their mates.

A matching is stable if there are no rogue couples.

** Example

**Four** people, **love triangle**. Alex who prefers Bobby Joe, Bobby Joe prefers Robin, and Robin prefers Alex. Then there is Mergatoid but nobody likes her.

*** Theorem

There doesn't exist a **stable** matching.

*** Proof by contradiction

Assume there \exists stable matching $M$. If it's a stable matching, Mergatoid has to be matched with somebody in $M$. Without loss of generality, assume Mergatoid is matched with Alex.

**WLOG (by symmetry)**, assume Mergatoid is matched to Alex.
Alex and Robin form a rogue couple $\implies$ $M$ is not stable

** Stable Marriage Problem

$N$ boys and $N$ boys (the same number of each).

Each boy has his own **ranked list** of all the girls. The same applies to girls.

*** Goal: Find Perfect Stable Matching

*** [PLACEHOLDER]
