** Algorithmic Complexity
:PROPERTIES:
:CUSTOM_ID: algorithmic-complexity
:END:
In principle, the /complexity/ of an algorithm is the dependence of the
number of operations that will be performed on the size of the input. It
is crucial to the computer system's scalability: it may be easy to solve
the programming problem for a particular set of inputs, but how will the
solution behave if the input is doubled or increased tenfold or
millionfold?

Let's look at the following illustrative example:

#+begin_src lisp
(defun mat-max (mat)
   (let (max)
     (dotimes (i (array-dimension mat 0))
       (dotimes (j (array-dimension mat 1))
         (when (or (null max)
               (> (aref mat i j) max))
         (setf max (aref mat i j)))))
    max))
#+end_src

This function finds the maximum element of a two-dimensional array
(matrix):

#+begin_src lisp
> *CL-USER> (mat-max #2A((1 2 3) (4 5 6)))*
6
#+end_src

There are six major complexity classes of algorithms: - Constant-time
(O(1)) - Sublinear (usually, logarithmic---O(log n)) - Linear (O(n)) and
superlinear (O(n * log n)) - Higher-order polynomial (O(nˆc), where c is
some constant greater than 1) - Exponential (O(cˆn), where c is usually
2 but, at least, greater than 1) - Just plain lunatic complex (O(n!) and
so forth)---I call them O(mg), jokingly

** Core Lisp
:PROPERTIES:
:CUSTOM_ID: core-lisp
:END:
[[ANSI Common Lisp]]

Lisp programs are supposed to be run not only in a one-off fashion of
simple scripts but also as live systems that operate over long periods
of time experiencing change not only of their data but also code. This
general way of interaction with a program is called Read-Eval-Print Loop
(REPL), which literally means that the Lisp compiler reads a form,
evaluates it with the aforementioned rule, prints the results back to
the user, and loops over.

*** Branching
:PROPERTIES:
:CUSTOM_ID: branching
:END:
Conditional expressions calculate the value of their \0irst form and,
depending on it, execute one of several alternative code paths. The
basic conditional expression is if:

#+begin_src lisp
    CL-USER> (if nil
                (print "hello")
                (print "world"))
    "world"
    "world"
#+end_src

As we've seen, nil is used to represent logical falsity, in Lisp. All
other values are considered logically true, including the symbol t which
directly has the meaning of truth. And when we need to do several things
at once, in one of the conditional branches, it's one of the cases when
we need to use progn or block :

#+begin_src lisp
    CL-USER> (if (+ 2 2)
                 (progn (print "hello")
                     4)
              (print "world"))
    "hello"
    4
#+end_src

The t case is a catch-all that will trigger if none of the previous
conditions worked (as its condition is always true). The preceding code
is equivalent to the following:

#+begin_src lisp
    (if (typep 4 'string)
        (print "hello")
        (if (> 4 2)
            (progn
              (print "world")
              nil)
              (print "can't get here")))
#+end_src

*** Looping
:PROPERTIES:
:CUSTOM_ID: looping
:END:
Lisp has a rich set of looping constructs, and it's also easy to define
new ones when necessary. This approach is different from the mainstream
languages that usually have a small number of such statements and,
sometimes, provide an extension mechanism via polymorphism. And it's
even considered to be a virtue justified by the idea that it's less
confusing for the beginners. It makes sense to a degree. Still, in Lisp,
both generic and custom approaches manage to coexist and complement each
other.

Anyway, for a complete beginner, actually, you have to know the same
number of iteration constructs as in any other language. The simplest
one is dotimes that iterates the counter variable a given number of
times (from 0 to (- times 1)) and executes the body on each iteration.
It is analogous to for (int i = 0; i < times; i++) loops found in C-like
languages:

#+begin_src lisp
    CL-USER> (dotimes (i 3)
               (print i))
    0
    1
    2
    NIL
#+end_src

The return value is nil by default, although it may be speci\0ied in the
loop header. The most versatile (and low-level) looping construct, on
the other hand, is do:

#+begin_src lisp
    CL-USER> (do ((i 0 (1+ i))
                  (prompt (read-line) (read-line)))
                 ((> i 1) i)
              (print (pair i prompt))
              (terpri))
    foo

    (0 "foo")
    bar

    (1 "bar")
    2
#+end_src

do iterates a number of variables (zero or more) that are defined in he
First part (here, i and prompt) until the termination condition in he
second part is satisfied (here, (> i 1)) and, as with dotimes (and other
do-style macros), executes its body---the rest of the forms (here, print
and terpri, which is a shorthand for printing a newline). read-line
reads from standard input until newline is encountered, and 1+ returns
the current value of i increased by 1. All do-style macros (and there's
quite a number of them, both built- in and provided from external
libraries: dolist, dotree, do- register-groups, dolines, etc.) have an
optional return value. In do, it follows the termination
condition---here, just return the final value of i. Besides do-style
iteration, there's also a substantially different beast in CL
ecosystem---the infamous loop macro. It is very versatile, although
somewhat unlispy in terms of syntax and with a few surprising behaviors.

*** Procedures and Variables
:PROPERTIES:
:CUSTOM_ID: procedures-and-variables
:END:
Procedures are the simplest way to reuse computations and they accept
arguments. A procedure in Lisp, is called lambda. You can define one
like this: (lambda (x y) (+ x y)) When used, such procedure will produce
the sum of its inputs:

#+begin_src lisp
    CL-USER> ((lambda (x y) + (+ x  y)) 2 2)
    4
#+end_src

It is quite cumbersome to refer to procedures by their full code
signature, and an obvious solution is to assign names to them. A common
way to do that in Lisp is via the defun macro:

#+begin_src lisp
    CL-USER> (defun add2 (x y) (+ x y))
    ADD2
    CL-USER> (add2 2 2)
    4
#+end_src

The arguments of a procedure are examples of variables. Variables are
used to name memory cells whose contents are used more than once and may
be changed in the process. They serve different purposes:

- To pass data into procedures
- As temporary placeholders for some varying data in code blocks, like
  loop counters
- As a way to store computation results for further reuse
- To define program configuration parameters (like the OS environment
  variables)
- To refer to global objects that should be accessible from anywher in
  the program

And more. So, how do we define variables in Lisp? You've already seen
some of the variants: procedural arguments and let bindings. Such
variables are called local or lexical in Lisp parlance. That's because
they're only accessible locally. /let/ is a general way to introduce
such local variables which is lambda in disguise:

#+begin_src lisp
    CL-USER> (let ((x 2))
              (+ x x))
    4
    CL-USER> ((lambda (x) (+ x x))
              2)
    4
#+end_src

While with lambda you can create a procedure in one place, possibly
assign it to a variable, and then apply many times in various places,
with let you define a procedure and immediately call it, leaving no way
to store it and reapply again afterward. Creating variables with let is
called binding. It is possible to bind several variables at once.

#+begin_src lisp
    CL-USER> (let ((x 2)
                    (y 2))
                (+ x y))
    4
#+end_src

In the code throughout this book, you'll only see these two binding
constructs: let for trivial and parallel bindings and with for all the
rest. As we said, variables may not only be defined, or they'd be called
"constants" instead, but also modified. To alter the variable's value,
we'll use the setf operator :

#+begin_src lisp
    CL-USER> (let ((x 2))
                (print (+ x x))
                (setf x 4)
                (+ x x))
    4
    8
#+end_src

Modification, generally, is a dangerous construct as it can create
unexpected action-at-a-distance effects, when changing the value of a
variable in one place of the code affects the execution of a different
part that uses the same variable. This, however, can't happen with
lexical variables: each let creates its own scope that shields the
previous values from modification (just as passing arguments to a
procedure call and modifying them within the call doesn't alter those
values, in the calling code):

The common way to define a global variable is with defparameter, which
specifies its initial value:

#+begin_src lisp
    (defparameter *connection* nil
           "A default connection object.") ; this is a
       docstring describing the variable
   #+end_src
#+end_src

Procedures in Lisp are first-class objects. This means the one you can
assign to a variable as well as inspect and redefine at runtime and,
consequently, do many other useful things with. The funcall operator 1
will call a procedure passed to it as an argument:

#+begin_src lisp
    CL-USER> (funcall 'add2 2 2)
        4
        CL-USER> (let ((add2 (lambda (x y) (+ x y))))
                    (funcall add2 2 2))
        4
#+end_src

*** Comments
:PROPERTIES:
:CUSTOM_ID: comments
:END:
This is how different comments may look like:

#+begin_src lisp
    ;;; Some code section
    (defun this ()
      "This has a curious docstring."
     ...)
    (defun that ()
     ...
    ;; this is an interesting block don't you find?
     (block interesting
      (print "hello"))) ; it prints hello
#+end_src

** Data Structures
:PROPERTIES:
:CUSTOM_ID: data-structures
:END:
From one point of view, algorithms are the essence of many programs,
while data structures may seem secondary. Besides, although a majority
of algorithms rely on certain features of particular data structures,
not all do. Good examples of the data-structure-relying algorithms are
heapsort, search using BSTs, and Union-Find. At the same time, some
seasoned developers state that when the right data structure is found,
the algorithm will almost write itself

The Art of Unix Programming by Eric S. Raymond as the "Rule of
Representation":

#+begin_quote
Fold knowledge into data so program logic can be stupid and robust. Even
the simplest procedural logic is hard for humans to verify, but quite
complex data structures are fairly easy to model and reason about. To
see this, compare the expressiveness and explanatory power of a diagram
of (say) a fifty-node pointer tree with a flowchart of a fifty-line
program. Or, compare an array initializer expressing a conversion table
with an equivalent switch statement. The difference in transparency and
clarity is dramatic. Data is more tractable than program logic. It
follows that where you see a choice between complexity in data
structures and complexity in code, choose the former. More: in evolving
a design, you should actively seek ways to shift complexity from code to
data.

#+end_quote

Data structures are more static than algorithms. Surely, most of them
allow change of their contents over time, but there are certain
invariants that always hold. This allows reasoning by simple induction:
consider only two (or at least a small number of) cases, the base one(s)
and the general. In other words, data structures remove, in the main,
the notion of time from consideration, and change over time is one of
the major causes of program complexity. In other words, data structures
are declarative, while most of the algorithms are imperative. The
advantage of the declarative approach is that you don't have to imagine
(trace) the flow of time through it.

Among Data Structures there are actually two distinct kinds: abstract
and concrete. The significant difference between them is that an
abstract structure is just an interface and a number of conditions or
invariants that have to be met. Their particular implementations, which
may differ significantly in efficiency characteristics and inner
mechanisms, are provided by the concrete data structures.

*** Contiguous and Linked Data Structures
:PROPERTIES:
:CUSTOM_ID: contiguous-and-linked-data-structures
:END:
The current computer architectures consist of a central processor,
memory and peripheral input-output devices. Data is exchanged via the IO
devices, stored in memory and processed by the CPU. There's a crucial
costraint called the von Neumann's bottleneck: the CPU can only process
data that is stored inside of it in a limited number of special basic
memory blocks called registers. So it has to constantly move data
elements back and forth between the registers and main memory (using
intermediate cache to speed up the process). Now there are things that
can fit in a register and those that cant't. The first ones are caleld
primitive and mostly unite those items that can be directly represented
with the integer numbers: integers proper, floats and characters.
Everything that requires a specific data structure to be represented
can't be put in a register as a whole.

Another item that fits into the processor register is a memory address.
In fact, there's an important constant - the number of bits in a
general-purpose register, which defines the maximum memory address that
a particular CPU may handle and, thus, the maximum amount of memory it
can work with. For a 32-bit architecture, it's 2^32 (4GB) and for 64-bit
it's 2^64. A memory address is usually called a /pointer/, and if you
put a pointer in a register, there are commands that allow the CPU to
retrieve the data in memory from where it points.

So there are two ways to place a data structure inside the memory:

- A contiguous structure occupies a single chunk of memory, and its
  contents are stored in adjacent memory blocks. To access a particular
  piece, we should know the offset of its beginning from the start of
  the memory range allocated to the structure. (This is usually handled
  by the compiler.) When the processor needs to read or write to this
  piece, it will use the pointer calculated as the sum of the base
  address of the structure and the offset. The examples of contiguous
  structures are arrays and structs.

- A linked structure, on the contrary, doesn't occupy a contiguous block
  of memory, that is, its contents reside in different places. This
  means that pointers to a particular piece can't be pre-calculated and
  should be stored in the structure itself. Such structures are much
  more flexible at the cost of this additional overhead both in terms of
  used space and time to access an element (which may require several
  hops when there's nesting, while in the contiguous structure, it is
  always constant). There exist a multitude of linked data structures
  like lists, trees, and graphs.

*** Tuples
:PROPERTIES:
:CUSTOM_ID: tuples
:END:
In most languages, some common data structures, like arrays or lists,
are built-in. To implement an arbitrary data structure, these languages
provide a special emchanism called records, structs objects and so on.
The proper name for it would be "tuple", which is an abstract data
structure, and its sole interface is the field accessor function: by
name, or index. It can be implemented in several ways. Python has a
dedicated tuple data type that is often used for this purpose, which is
a linked data structure under the hood. The following Python function
will return a tuple (written in parens) of a decimal and remainder parts
of the number x:

#+begin_src python
    def truncate(x):
        dec = int(x)
        rem = x - dec
        return (dec, rem)
#+end_src

A better approach both from the point of view of efficiency and code
clarity is to use a predefined structure. In Lisp, a tuple is called
"struct" and is defined with defstruct, which uses a contiguous
representation by default.

#+begin_src lisp
    (defstruct pair
            left right)
#+end_src

The defstruct macro generates several definitions the struct type, its
constructor that will be called make-pair and have two keyword arguments
:left and :right and field accessors pair-left and pair-right.

*** Passing Data Structures in Function Calls
:PROPERTIES:
:CUSTOM_ID: passing-data-structures-in-function-calls
:END:
There are two ways to use data structures with functions: pass them
directly via copying memory areas (call-by-value), or pass a pointer
(call-by-reference). The difference between the two, is that in
call-by-value there is no way to modify the contents of the original
structure, but in call-by-reference it's possible and is also the more
general and efficient approach. It's the default way to handle
structures. In C, both are supported.

*** Structs in Actions: Union-Find
:PROPERTIES:
:CUSTOM_ID: structs-in-actions-union-find
:END:
Union-Find is a family of data structure-- algorithms that can be used
for efficient determination of set membership in sets that change over
time. They may be used for finding the disjoint parts in networks,
detection of cycles in graphs, finding the minimum spanning tree, and so
forth.

Let's consider the following problem: How to determine if two points of
the graph have a path between them, given a graph that is a set of
points (vertices) and edges between some of the pairs of these points? A
path in the graph is a sequence of points leading from source to
destination with each pair having an edge that connects them. If some
path between two points exists, they belong to the same component, and
if it doesn't, to two disjoint ones.

The Union-Find approach is based on a simple idea: when adding, the
items record the id of the component they belong to.

#+begin_src lisp
    (defstruct point
      parent) ; if the parent is null the point is
    the root
    (defun uf-union (point1 point2)
     "Join the subsets of POINT1 and POINT2."
     (setf (point-parent point1) (or (point-parent
                                      point2)
                                  point2)))
    (defun uf-find (point)
     "Determine the id of the subset that a POINT
    belongs to."
     (let ((parent (point-parent point)))
      (if parent
       (uf-find parent)
       point)))
#+end_src

** Arrays
:PROPERTIES:
:CUSTOM_ID: arrays
:END:
Arrays are one of the most basic data structure and they're often the
default choice for implementing algorithms of sort.

#+begin_src lisp
CL-USER> (make-array 3)

# (0 0 0)
#+end_src

The printed result is the literal array representation. It happens that
the array is shown to hold 0s, but that's the implementation dependent.
Additional specifics can be set during array initialization for
instance: element-type, :initial-element and even full contents”

#+begin_src lisp
CL-USER> (make-array 3 :element-type 'list
:initial-element nil)
#(NIL NIL NIL)
CL-USER> (make-array 3 :initial-contents '(1.0 2.0
3.0))
#(1.0 2.0 3.0)
#+end_src

*** Multidimensional Arrays
:PROPERTIES:
:CUSTOM_ID: multidimensional-arrays
:END:
There are a staggering variety of other structures that can be built on
top of arrays, such as binary (or, in fact, any n-ary) trees,
hash-tables, and graphs, to name a few. If we have a chance to implement
the data structure on an array, usually, we should not hesitate to take
it as it will result in constant access time, good cache locality
contributing to faster processing, and, in most cases, efficient space
usage.

/Multidimensional arrays/ are a contiguous data structure that stores
its elements so that, given the coordinates of an element in all
dimensions, it can be retrieved according to a known formula. Such
arrays are also called tensors and, in the case of two-dimensional
arrays, matrices. We have already seen one matrix /example/ in the
discussion of complexity:

#+begin_src lisp
#2A ((1 2 3)
     (4 5 6))
#+end_src

A *matrix* has rows (first dimension) and columns (second dimension).

*** Binary Search
:PROPERTIES:
:CUSTOM_ID: binary-search
:END:
The simple way to search for an element in Lisp is using the function
find :

#+begin_src lisp
CL-USER> (let ((vec (make-array 2 :initial-  
    contents  
                                  (list (rtl:pair  
:foo :bar)  
                                        (rtl:pair  
:baz :quux)))))  
           (print (find (rtl:pair :foo :bar) vec))  
           (print (find (rtl:pair :foo :bar) vec  
:test 'equal))  
           (print (find (rtl:pair :bar :baz) vec  
:test 'equal))  
           (print (find :foo vec :key 'lt)))  
NIL  
(:FOO :BAR)  
NIL  
(:FOO :BAR)
#+end_src

In the first case, the element was not found due to the wrong\\
comparison predicate: the default eql will only consider two\\
structures to be the same if they're the same object, and, in this
case,\\
there will be two separate pairs with the same content.

The second search is successful as equal performs deep comparison. Such
search is called sequential scan because it is performed in a\\
sequential manner over all elements of the vector starting from the\\
beginning

If we know that our sequence is sorted, we can perform\\
the search much faster. The algorithm used for that is one of the most\\
famous algorithms that every programmer has to know and use, from\\
time to time---binary search. The more general idea behind it is called
/"divide and conquer":/ if there's some way, looking at one element,
to\\
determine the outcome of our global operation for more than just this\\
element, we can discard the part for which we already know that the\\
outcome is negative. In *binary search*, when we're looking at an\\
arbitrary element of the sorted vector and compare it with the item we\\
search for

- If the element is the same, we have found it.\\
- If it's smaller, all the previous elements are also smaller and thus\\
- uninteresting to us---we need to look only on the subsequent ones.\\
- If it's greater, all the following elements are not interesting.

Here's an "optimized" version of binary search that returns\\
three values:\\
- The final element of the array.\\
- Its position.\\
- Has it, actually, matched the element we were searching for?

#+begin_src lisp
(defun bin-search (val vec &key (less '<) (test  
'=) (key 'identity))  
    (when (plusp (length vec))  
    (let ((beg 0)  
        (end (1- (length vec))))  
     (do ()  
        ((= beg end))  
    (let ((mid (+ beg (floor (- end beg) 2))))  
        (if (funcall less (funcall key (aref vec  
mid)) val)  
            (setf beg (1+ mid))

            (setf end mid))))  
        (values (aref vec beg)  
                beg  
                (funcall test (funcall key (aref vec  
beg)) val)))))
#+end_src

The number of iterations needed to expand the full array may be
calculated by the\\
inverse of exponentiation---the logarithmic function. That is, we'll
need\\
*(log n 2)* iterations (where n is the initial array size). Shrinking
the\\
array takes the same as expanding, just in the opposite order, so the\\
complexity of binary search is *O(log n)*.

Here's a speed comparison:

#+begin_src lisp
CL-USER> (rtl:with ((size 100000000)  
                    (mid (1+ (/ size 2)))  
                    (vec (make-array size)))  
            (dotimes (i size)  
                (setf (aref vec i) i))  
            (time (find mid vec))  
            (time (bin-search mid vec)))  
Evaluation took:  
    0.591 seconds of real time  
    0.595787 seconds of total run time (0.595787  
user, 0.000000 system)  
    100.85% CPU  
    ...  
Evaluation took:  
    0.000 seconds of real time
    0.000000 seconds of total run time (0.000000  
user, 0.000000 system)  
    100.00% CPU  
    ...
#+end_src

The *crucial limitation* of binary search is that it requires our\\
sequence to be presorted because sorting before each search already\\
requires at least linear time to complete, which kills any performance\\
beneit we might have expected. Obviously, it will only work fast for\\
*vectors* and not linked sequences.

** Sorting
:PROPERTIES:
:CUSTOM_ID: sorting
:END:
Unlike searching, there is no single optimal algorithm for sorting.
Several aspects differentiate sorting functions:

- *In-place*: This kind of sorting is a destructive operation, but it is
  often\\
  desired because it may be faster and also it preserves space. The
  alternative is copying sort.
- *Stable*: Whether two elements, which are considered the same by the\\
  predicate, retain their original order or may be shufled.
- *Online*: Does the function require the whole sequence before starting
  the sorting process?

An ideal algorithm should show better than average performance (up to
*O(1)*)\\
on the sorted and almost sorted special cases. *Sorting* was and still
remains a popular research topic. Not surprisingly, several dozens of
different sorting\\
algorithms were developed. But before discussing the prominent ones,\\
let's talk about "stupid sort" (or "*bogosort*"). In the case of
bogosort, the\\
number of possible inputs is the number of all permutations that's equal
to n!, so considering that we need to also examine each permutation's
order, the algorithm's complexity is *O(n * n!)*.

#+begin_src lisp
(defun bogosort (vec comp)  
    (dolist (variant (all-permutations vec))  
        (dotimes (i (1- (length variant)))  
                    ;; this is the 3rd optional  
                    ;; argument of dotimes header  
                    ;; that is evaluated only after  
                    ;; the loop finishes normally  
                    ;; if it does we have found a  
                    ;;completely sorted permutation!  
                    (return-from bogosort variant))  
        (when (funcall comp (aref variant (1+ i))  
(aref variant i))  
        (return))))) ; current variant is not  
sorted, skip it
#+end_src

*** O(n^2) Sorting
:PROPERTIES:
:CUSTOM_ID: on2-sorting
:END:
Bogosort gives us a good lower bound on the sorting\\
algorithm's performance. There are a number of simple algorithms that
work in quadratic time and that are far more efficient than bogosort.
One of the most well known is "*Bubble Sort*", but it's not too
straightforward and has poor performance characteristics too, and for
that reason is rarely used. Two simple quadratic algorithms that are
actually useful are:

- Selection Sort
- Insertion Sort

Selection Sort is an in-place sorting algorithm that moves left to right
from the beginning of the vector one element at a time and builds the
sorted prefix to the left of the current element. This is done by
finding the largest element in the right part and swapping it with the
current element:

#+begin_src lisp
(defun selection-sort (vec comp)  
    (dotimes (i (1- (length vec)))  
        (let ((best (aref vec i))  
                (idx i))  
            (dotimes (j (- (length vec) i 1))  
                (when (call comp (aref vec (+ i j 1))  
best)  
            (setf best (aref vec (+ i j 1))  
                idx (+ i j 1))))  
        (rotatef (aref vec i) (aref vec idx)))) ;  
this is the Lisp swap operator  
    vec)
#+end_src

This algorithm requires a constant number of operations regardless of
the level of sortedness: =(/ (* n (- n  1)) 2)= --- the sum of the
arithmetic progression from 1 to n, because at each step, it needs to
fully examine the remainder of the lements to find the maximum and the
remainder's size varies from n to 1. It handles well both contiguous and
linked sequences. The Insertion Sort is another quadratic-time in-place
sorting algorithm. This one, instead of looking for the global maximum
on the right-hand side, it looks for a proper place of the current
element on the left-hand side. As this part is always sorted, it takes
linear time to find the place for the new element and insert it
accordingly. This has great implications:

- It is stable;
- It is online. In contrat with selection sort, it doesnt't have to find
  the maximum element of the sequence in the first step;
- For sorted sequences, it works in linear time. However, for reverse
  sorted sequences, its performance will be the worse *O(k * n)*, where
  k is the average offset of the element. For sorted sequences k=0 and
  for reverse sorted sequences, it's =(/ (- n 1)  2)=;

#+begin_src lisp
(defun insertion-sort (vec comp)  
    (dotimes (i (1- (length vec)))  
        (do ((j i (1- j)))  
            ((minusp j))  
          (if (funcall comp (aref vec (1+ j)) (aref  
vec j))  
            (rotatef (aref vec (1+ j)) (aref vec j))  
            (return))))  
    vec)
#+end_src

The implementation is simple: we look at each element starting from the
second an compare it to the previous element, and if it's better, we
swap them and continue the comparison with the previous element until we
reach the array's beginning. So, when it comes to actual processing
time, which one is better?

If we compare them when taking into analysis the average case, we'll get
the following numbers:

- Selection sort:
  =(+ (/ (* n (- n 1)) 2) (/ n 2)) = (/  (+ (* n n) n) 2)=
- Insertion sort:
  =(+ (/ (* n (- n 1)) 2) (+ (/ (* (- n  1) (- n 2)) 4) = (/ (+ (* 1.5 n n) (* -2.5 n) 1)  2)=

The second number is slightly higher than the first. For small =n=s it
is almost negligible, but for huge ones, insertion sort will need *1.5
times* more operations. It is also the case that swaps are more
expensive than comparisons. In practice, insertion sort ends up being
used more often. In general, quadratic sorts are only used when the
input array is *small*.

** Quicksort
:PROPERTIES:
:CUSTOM_ID: quicksort
:END:
There are a number of other *O(n^2)* sorting algorithms similar to\\
selection and insertion sorts, but studying them quickly turns boring,\\
so we won't, as there are also a number of signiicantly faster\\
algorithms that work in *O(n * log n)* time /(almost linear)/.

They rely on the /divide-and-conquer/ approach. Probably, the most
famous of such algorithms is quicksort. Its idea is, at each iteration,
to select some element of the array as the "*pivot*" point and divide
the array into two parts---all the elements that are\\
smaller and all those that are larger than the pivot---and then
recursively sort each subarray. As all left elements are below the pivot
and all right above, when we manage to sort the left and right sides,
the whole array will be sorted. This invariant holds for all iterations
and for all subarrays.

There're several tricks in quicksort implementation. The first one has
to do with pivot selection. Let's say that all elements are greater than
the pivot---then the pivot will be at index 0. Now, if moving left to
right over the array we encounter an element that is not\\
greater than the pivot, we should put it before, that is, the pivot's
index\\
should increment by 1. When we reach the end of the array, we know\\
the correct position of the pivot, and in the process, we can swap all
the\\
elements that should precede it in front of this position. We have then
to put the element that is currently occupying the pivot's place
somewhere. The most obvious thing is to swap it with the pivot:

#+begin_src lisp
(defun quicksort (vec comp)  
    (when (> (length vec) 1)  
      (with ((pivot-i 0)  
            (pivot (aref vec (1- (length vec)))))  
        (dotimes (i (1- (length vec)))  
          (when (funcall comp (aref vec i) pivot)  
            (rotatef (aref vec i)  
                     (aref vec pivot-i))  
            (incf pivot-i)))  
            ;; swap the pivot (last element) in its  
            ;; proper place  
        (rotatef (aref vec (1- (length vec)))  
                (aref vec pivot-i))  
        (quicksort (rtl:slice vec 0 pivot-i) comp)  
        (quicksort (rtl:slice vec (1+ pivot-i))  
comp)))  
    vec)
#+end_src

Let's consider the complexity of this implementation. If on every
iteration, we divide the array in two equal halves, we'll need to
perform =n= comparisons and =n/2= swaps and increments, which totals to
=2n= operations. We'll also need to do that =(log n 2)=, which is the
height of a complete binary tree with =n= elements.. At every level of
the recursion tree, we'll need to perform twice as many sorts with twice
as little data, so each levels equals to a =2n= operations number. Total
complexity would then be =2n * (log n 2)= which become, when in the
ideal case, **O(n * log n*)**.

However, we cannot guarantee that the selected pivot will divide the
array into two ideally equal parts. In the worst case, if we were to
split it into two totally unbalanced subarrays, with n-1 and 0 elements,
respectively, we'd need to perform sorting n times and perform a number
of operations that will diminish in the arithmetic progression from 2n
to 2. This sums to (* n ( - n 1)), a dreaded *O(n^2)* complexity.

So the worst-case performance for quicksort is not just worse, but in a
different complexity league than the average-case one. Moreover, the
conditions for such performance are not so uncommon: sorted and reverse
sorted arrays. It is also interesting to note that if, at each stage, we
were to split\\
the array into parts that have a 10:1 ratio of lengths, this would
have\\
resulted in n * log n complexity.

Dealing with equal elements is another corner case for quicksort\\
that should be addressed properly. The ix is simple: to divide the
array\\
not in two but three parts, smaller, larger, and equal to the pivot.
This\\
will allow for the removal of the equal elements from further\\
consideration and will even speed up sorting instead of slowing it\\
down.

** Linked Lists
:PROPERTIES:
:CUSTOM_ID: linked-lists
:END:
*Linked* data structures are in many ways the /opposite/ of the
contiguous ones that we have explored to some extent in the previous
chapter using the example of arrays. In terms of complexity, they fail
where those ones shine (first of all, at random access), but prevail at
scenarios when a repeated modiication is necessary. In general, they are
much more lexible and so allow the programmer to represent almost any
kind of a data structure, although the ones that require such level of
lexibility may not be too frequent. Usually, they are specialized trees
or graphs.\\
The basic linked data structure is a singly linked list.

Just like arrays, lists in Lisp may be created both with a literal\\
syntax for constants and by calling a function---make-list---that\\
creates a list of a certain size illed with nil elements. Besides,
there's\\
a handy list utility that is used to create lists with the speciied\\
content (the analog of rtl:vec):

#+begin_src lisp
CL-USER> '("hello" world 111)  
("hello" WORLD 111)  
CL-USER> (make-list 3)  
(NIL NIL NIL)  
CL-USER> (list "hello" 'world 111)  
("hello" WORLD 111)
#+end_src

** Lists as Sequences
:PROPERTIES:
:CUSTOM_ID: lists-as-sequences
:END:
Alongside arrays, list is the other basic data structure that implements
the sequence abstract data type. Let's consider the complexity of basic
sequence operations for linked lists:

- So-called random access, that is, access by index of a random\\
  element, requires O(n) time as we have to traverse all the preceding\\
  elements before we can reach the desired one (n/2 operations on\\
  average).\\
- Yet, once we have reached some element, removing it or inserting\\
  something after it takes O(1).\\
- Subsequencing is also O(n).

Getting the list length, in the basic case, is also O(n), that is, it\\
requires full list traversal. It is possible, though, to store list
length as a\\
separate slot, tracking each change on the ly, which means O(1)\\
complexity. Lisp, however, implements the simplest variant of lists\\
without size tracking.

This is an example of a small but important decision that real-world
programming is full of. Why is such a solution the right thing in this
case? Adding the size counter to each list would have certainly made
this common length operation more effective, but the cost of doing that
would've included increase in occupied storage space for all lists, a
need to update size in all list modiication operations, and, possibly, a
need for a more complex cons cell implementation.

** Lists as Functional Data Structures
:PROPERTIES:
:CUSTOM_ID: lists-as-functional-data-structures
:END:
Singly linked lists are a simple example of functional data structures.
A functional or persistent data structure is the one that doesn't allow
in-place modiication. In other words, to alter the contents of the
structure, a fresh copy with the desired changes should be created. The
lexibility of linked data structures makes them suitable for serving as
functional ones. We have seen the cons operation that is one of the
earliest examples of nondestructive, that is, functional, modiication.
This action prepends an element to the head of a list, and as we're
dealing with the singly linked list, the original doesn't have to be
updated: a new cons cell is added in front of it with its next pointer
referencing the original list that becomes the new tail. This way, we
can both preserve the pointer to the original head and add a new head

** Key Values
:PROPERTIES:
:CUSTOM_ID: key-values
:END:
/Key-values/ (kvs) are the broadest family of structures one can
imagine. Unlike arrays and lists, kvs are not concrete structures. In
fact, they span, at least in some capacity, all of the popular concrete
ones, as well as some obscure.

The main feature of kvs is eficient accessto the values by some kind of
keys that they are associated with. In other words, each element of such
data structure is a /key-value pair/ that can be easily retrieved if we
know the key, and, on the other hand, if we ask for the key that is not
in the structure, the null result is also returned eficiently. By
"efficiently," we usually mean /O(1)/ or, at least, something sublinear
(like /O(log n/)), although, for some cases, even /O(n)/ retrieval time
may be acceptable. See how broad this is! So a lot of different
structures may play the role of key-values.

They are essential to some dynamic languages such as Lua or Javascript.
They have different names, such as hash-tables, maps, dictionaries,
associative arrays, tables and so on, and Lisp was one of the first
languages to have them natively supported.

*** Simple Arrays
:PROPERTIES:
:CUSTOM_ID: simple-arrays
:END:
Simple sequences, especially arrays, may be regarded as a particular
variant of kvs that allows only numeric keys with eficient (and fastest)
constant-time access. This restriction is serious. However, as we'll see
in the following, it can often be worked around with clever algorithms.

As a result, arrays actually play a major role in the key-value space,
but not in the most straightforward form. However, if it is possible to
be content with numeric keys and their number is known beforehand,
vanilla arrays are the best possible implementation option.

Let's see what concrete structures can be considered key-values and in\\
which cases it makes sense to use them.

*** Associative Lists
:PROPERTIES:
:CUSTOM_ID: associative-lists
:END:
The main drawback of using simple arrays for kvs is not even the
restriciton that all keys should somehow be reduced to numbers, but the
static nature of arrays that do not lend themselves well to resizing. As
an alternative we could use linked lists, which do not have this
restriction. If the key value contains many elements, linked lists are
clearly not ideal in terms of efficiency

*** Hash Tables
:PROPERTIES:
:CUSTOM_ID: hash-tables
:END:
Hash-tables are probably the *most common* way to do key-values. They are dynamic and don't impose restrictions on keys while also having an amortized O(1) perfomance. They come in several different "flavors" and are the most versatile key-value variant and thus the default choice for such a structure.

*** Structs
:PROPERTIES:
:CUSTOM_ID: structs
:END:
Structs may be considered a special *variant* of key-values with a predefined set of keys. In this respect, structs are similar to arrays, which have a fixed set of keys (from 0 to MAX_KEY).
Generally, structs internally map to arrays, so they may be considered a layer of syntactic sugar that provides names for the keys and handy accessors

*** Trees
:PROPERTIES:
:CUSTOM_ID: trees
:END:
Another versatile option for implementing kvs is by using trees. There are even more tree variants than hash-tables. The main advantage of trees compared to simple hash-tables is the possibility to impose some ordering on the keys. Also, trees don't require hashing.

*** Operations
:PROPERTIES:
:CUSTOM_ID: operations
:END:
The primary operation for a kv structure is access to its elements by key: to set, change and remove. As there are so many different variants of concrete vkvs, there are a number of different low-level access operations.

*** Memoization
One of the major use cases for key-valuse is *memoization*, which is storing the results of previous computations in a dedicated table (cache) to avoid recalculating them.
/Transposition tables/ are a characteristic example of the effective usage of memoization, which comes from a classic game AI. But the same approach may be applied in numerous other areas with lots of computation paths that converge and diverge at times.In such games as chess, the same position may be reached in a great variety of moves.

All possible sequences are called *transpositions*, and it is obvious that, regardless of how we reached a certain position, if we have already analyzed that situation previously, we don’t need to repeat the analysis when it repeats. So caching the results allows avoiding a lot of redundant computation.

However, the number of positions, in chess, that comes up during the analysis is huge, so we don’t stand a chance of remembering all of them. In this case, a good predictor for the chance of a situation to occur is very likely the number of times it has occurred in the past. For that reason, an appropriate caching technique, in this context, is plain LFU (least frequently used).

*** LFU
An algorithm that uses a counter instead of a lag will be called least frequently used (LFU) item eviction.There is one problem though: the access counter will only grow overtime, so some items that were heavily used during some period willnever be evicted from the cache, even though they may never be accessed again.
To counteract this accumulation property, which is similar to bitmap saturation we’ve seen in the previous algorithm, a similar measure can be applied. Namely, we’ll have to introduce some notion of epochs, which reset or diminish the value of all counters. The most common approach to epochs is to right shift each counter, that is, divide by 2. This strategy is called aging . An LFU cache with aging may be called LRFU—least recently/frequently used.

*** LRU
Is an alternative to LRU, evict the item that was used the longest time ago. LRU means that we need to store either last-access timestamps or some generation/epoch counters. Another possibility is to utilize access coutners, similar to the ones that were used for LFU,


** Hash-Tables
The basic properties of hash-tables are average O(1) access and support for arbitrary keys. These features can be realized by storing the items in an array at indices determined by a specialized function that maps the keys in a pseudo-random way.

*** Dealing with Collisions
Even better would be if there were no collisions (situations where two or more keys are mapped to the same index). For dynamic hash-tables, we have to accept that collisions are inevitable.

The probability of collisions isgoverned by an interesting phenomenon called “the Birthday Paradox.”Let’s say we have a group of peopleof some size, for instance, 20. What is the probability that two of them have birthdays on the same date?
It may seem quite improbable, considering that there are 365 days in a year and we are talking just about a handful of people. But if you take into account that we need to examine each pair of people to learn about their possible birthday collision, that will give us (/ (* 20 19) 2), that is, 190 pairs.
We can calculate the exact probability by taking the complement to the probability that no one has a birthday collision, which is easier to reason about. The probability that two people don’t share their birthday is (/ (- 365 1) 365): there’s only one chance in 365 that they do.
For three people, we can use the chain rule and state that the probability that they don’t have a birthday collision is a product of the probability that any two of them don’t have it and that the third person also doesn’t share a birthday with any of them.
This results in (* (/364 365) (/ (- 365 2) 365)). The value (- 365 2) refers to the third person not having abirthday intersection with neither the first nor the second individually, and those are distinct, as we have already asserted in the first term.
Continuing in such fashion, we can count the number for 20 persons:

#+begin_src lisp :tangle yes
(defun birthday-collision-prob (n)
    (let (rez 1))
        (dotimes (i n)
          (setf rez (* rez (/ (- 365 i) 365))))
#+end_src

#+begin_src lisp :tangle yes
CL-USER> (birthday-collision-prob 20)
0.4114384
#+end_src

So among 20 people there's already a 40% chance of observing a coinciding birthday.
Well, if you substitute keys for persons and the array size for the number of days in a year, you'll get the formula of the probability of at least one collision among the hashed keys in an array, provided the hash-function produces perfectly uniform output.

#+begin_src lisp :tangle yes
(defun hash-collision-prob (n size)
    (let ((rez 1))
        (dotimes i n))
            (setf rez (* rez (/ (- size i) size))))
    (- 1.0 rez)

#+end_src

Let's say we have ten keys. What should be the array size to be safe against collisions?

#+begin_src lisp :tangle yes
CL-USER> (hash-collision-prob 10 10)
0.9996371
#+end_src

Which means we don't stand a chance to accidentally get a perfect layout. Collisions /ARE/ inevitable.
How can we deal with this issue? We need to have a fallback option: when two keys hash to the same index, store both of them inside a list. The retrieval operation in this case will require a sequential scan to find the requested key and return the corresponding value. Such an approach is called /chaining/.
It has a number of drawbacks:

- It complicates the implementation: now we have to deal with both a static array and a dynamic list/array/tree.
- It requires more memory
- It will have poor performance due to the necessity of dealing with a linked structure and, what's worse, not respecting cache locality: the chain won't fit in the original array so at least one additional RAM round-trip will be required.

The more widely used alternative to chaining is called "*open addressing*" or "*closed hashing*". With ith, the chains are, basically, stored in the same backing array. The algorithm is simple: when the calculated hash is pointing at an already occupied slot in the array, find the next vacant slot by cycling over the array. If the table isn't full, we're guaranteed to find one. If it isfull, we need to resize it first. Now, when the element is retrieved by key, we need to perform the same procedure: calculate the hash and then compare the key of the item at the returned index. If the keys are the same, we've found the desired item, otherwise we need to cycle over the array comparing keys.

An hash-table is priarily parametrized by two things: the hash function and the equality predicate. In Lisp, in particular, there's a choice of just the four standard equality predicates: eq,eql,equal and equalp
The following approach is sufficient for the majority of the hash-table use case:

- Use the eql predicate if the keys are numbers, characters or symbol.
- Use equal if the keys are strings or lists of the mentioned items.
- Use equalp if the keys are vectors, structs or anything else containing one of those.

*** Advanced Hashing Techniques
Beyond the direct implementation of open addressing called "*linear probing*" (for it tries to resolve collisions by performing a linear scan for an empty slot) a number of approaches were proposed to improve hash distribution and reduce the collision rate.
The simplest modification of linear probing is called "*quadratic probing*". It operates by performing the search for the next vacant slot using the linear probing offsets that are just raised to the power 2.
"*Double hashing*" is another simple alternative. This approach makes the sequence specific to each key, so the keys that map to the same location will have different possible variants of collision resolution.
"*2-choice hashing*" also uses two hash-functions but selects the particular one for each key based on the distance from the original index it has to be moved for collision resolution.
