#+begin_src lisp
(defun ask-number ()
    (format t "Please enter a number. ")
    (let ((val (read)))
        (if (numberp val)
            val
            (ask-number))))
#+end_src

This function creates a variable v a l to hold the object returned by
read. Because it has a handle on this object, the function can look at
what you entered before deciding whether or not to return it. As you
probably guessed, =numberp= is a predicate that tests whether its
argument is a number.

If the value entered by the user isn't a number, ask-number calls
itself. The result is a function that insists on getting a number:

#+begin_src lisp
> (ask-number)
Please enter a number, a
Please enter a number, (ho hum)
Please enter a number. 52
52
#+end_src

Variables like those we have seen so far are called local variables.
They are only valid within a certain context. There is another kind of
variable, called a global variable, that can be visible everywhere.

You can create a global variable by giving a symbol and a value to
=defparameter=:

#+begin_src lisp
> (defparameter *glob* 99)
*GLOB*
#+end_src

Such a variable will then be accessible everywhere, except in
expressions that create a new local variable with the same name. To
avoid the possibility of this happening by accident, it's conventional
to give global variables names that begin and end with asterisks.

The name of the variable we just created would be pronounced
"star-glob-star".

You can also define global constants, by calling def constant:

#+begin_src lisp
(defconstant limit (+ *glob* 1))
#+end_src

If you want to check whether some symbol is the name of a global
variable or constant, use =boundp=:

#+begin_src lisp
> (boundp '*glob*)
T
#+end_src

In Common Lisp the most general assignment operator is setf. We can use
it to do assignments to either kind of variable:

#+begin_src lisp
> (setf *glob* 98)
98
> ( let ((n 10))
        (setf n 2)
        n)
2
#+end_src

** *Functional Programming*
:PROPERTIES:
:CUSTOM_ID: functional-programming
:END:
Functional programming means writing programs that work by returning
values, instead of by modifying things. It is the dominant paradigm in
Lisp.

Most built-in Lisp functions are meant to be called for the values they
return, not for side-effects.

The function remove, for example, takes an object and a list and returns
a new list containing everything but that object:

#+begin_src lisp
> (setf 1st '(c a r a t))
(C A R A T)
> (remove 'a 1st)
(C R T)
#+end_src

The original list is untouched afterwards:

#+begin_src lisp
> 1st
(C A R A T)
#+end_src

So what if you really do want to remove something from a list? In Lisp
you generally do such things by passing the list as an argument to some
function, and using setf with the return value. To remove all the as
from a list x, we say:

#+begin_src lisp
(setf x (remove `a x))
#+end_src

Functional programming means, essentially, avoiding setf and things like
it. At first sight it may be difficult to imagine how this is even
possible, let alone desirable. How can one build programs just by
returning values?

** Iteration
:PROPERTIES:
:CUSTOM_ID: iteration
:END:
When we want to do something repeatedly, it is sometimes more natural to
use iteration than recursion. A typical case for iteration is to
generate some sort of table. This function

#+begin_src lisp
(defun show-squares (start end)
    (do (( i start (+ i 1)))
            ((> i end) 'done)
        (format t "~A ~k~l" i (* i i))))
#+end_src

prints out the squares of the integers from start to end:

#+begin_src lisp
> (show-squares 2 5)
2 4
3 9
4 16
5 25
DONE
#+end_src

Recursive version of =show-squares=:

#+begin_src lisp
(defun show-squares (i end)
    (if (> i end)
            'done
            (progn
                (format t "~A ~A~%" i (* i i ))
                (show-squares (+ i 1) end))))
#+end_src

=progn=: /it takes any number of expressions, evaluates them in order,
and returns the value of the last./

To iterate through the elements of a list, for example, you would be
more likely to use =dolist=.

Here is a function that returns the length of a list:

#+begin_src lisp
(defun our-length (1st)
    (let ((len 0))
        (dolist (obj 1st)
            (setf len (+ len 1)))
        len))
#+end_src

Here =dolist= takes an argument of the form (variable expression),
followed by a body of expressions. The body will be evaluated with
variable bound to successive elements of the list returned by
expression. So the loop above says, for each obj in 1st, increment len.

The obvious recursive version of this function would be:

#+begin_src lisp
(defun our-length (1st)
    (if (null 1st)
            0
            (+ (our-length (cdr 1st)) 1)))
#+end_src

** Functions as Objects
:PROPERTIES:
:CUSTOM_ID: functions-as-objects
:END:
In Lisp, functions are regular objects, like symbols or strings or lists

Like quote, function is a special operator.

#+begin_src lisp
> (function +)
#<Compiled-Function + 17BA4E>
#+end_src

Just as we use =as an abbreviation for quote, we can use #= as an
abbreviation for function.

#+begin_src lisp
> #' +
#<Compiled-Function + 17BA4E>
#+end_src

This abbreviation is known as sharp-quote. Like any other kind of
object, we can pass functions as arguments. One function that takes a
function as an argument is apply. It takes a function and a list of
arguments for it, and returns the result of applying the function to the
arguments:

#+begin_src lisp
> (apply #'+ ' ( 1 2 3))
6
> (+ 1 2 3)
6
#+end_src

** What is Lambda?
:PROPERTIES:
:CUSTOM_ID: what-is-lambda
:END:
The lambda is not an operator, but just a symbol =°=. In the earlier
dialects of Lisp, it was used to tell a function from a ordinary list
because functions were represented as lists (lambda as the first
element). In Common Lisp, it is no longer required.

#+begin_src lisp
((x) (+ x 100))

instead of

(lambda (x) (+ x 100)
#+end_src

Functions have no need to have a name, nor do we have to define them
using =defun= .

We can instead refer to functions literally. To refer literally to an
integer, we use a series of digits; to refer literally to a function, we
use what's called a lambda expression, which is a list containing the
symbol lambda, followed by a list of parameters, followed by a body of
zero or more expressions.

#+begin_src lisp
(lambda (x y)
    (+ x y))
#+end_src

The list (x y) is the parameter list, and right after there is the body
of the function. A lambda expression can be considered as the name of a
function. Like an ordinary function name, a lambda expression can be the
first element of a function call

#+begin_src lisp
> ((lambda (x) (+ x 100)) 1)
101
#+end_src

and by affixing a sharp-quote to a lambda expression, we get the
corresponding function

#+begin_src lisp
> (funcall #`(lambda (x) (+ x 100))
                     1)
101
#+end_src

Among other things, this notation allows us to use functions without
naming them.

** Symbols
*** Symbol Names
The range of possible Lisp symbols is broader than the range of variable names allowed in most languages. In fact, a symbol can have any string as its name. You can get the name of a symbol by calling symbol-name:

#+begin_src lisp :tangle yes
> (symbol-name 'abc)
"ABC"
#+end_src

By default Common Lisp converts all alphabetic characters in a symbol's name into uppercase as they are read. In fact, CLisp is not case-sensitive.

*** Property Lists
In Common Lisp every symbol has a property-list, or plist. The function get takes a symbol and a key of any type, and returns the value associated with that key in the symbol's property list:

#+begin_src lisp :tangle yes
> (get 'alizarin 'color')
NIL
#+end_src

It uses *eql* to compare keys. If the specified property isn't found, get returns nil. To associate a value with a key you can use setf with get:

#+begin_src lisp :tangle yes
> (setf (get 'alizarin 'color) 'red')
RED
> (get 'alizarin 'color)
RED
#+end_src

The function symbol-plist returns the property list of a symbol:

#+begin_src emacs-lisp :tangle yes
> (setf (get 'alizarin 'transparency) 'high')
HIGH
> (symbol-plist 'alizarin)
(TRANSPARENCY HIGH COLOR RED)
#+end_src

Property lists aren't used much, as they have been largely superseded by hash tables.

* Macros

The most common way to write programs that write programs is by defining *macros*. /Macros/ are /operators/ that are implemented by /transformation/. You define a macro by saying how a call to it should be translated. This translation, called macro-expansion, is done automatically by the compiler. So the code generated by your macros becomes an integral part of your program, just as if you had typed it in yourself. Macros are usually defined by calling defmacro. A defmacro looks a lot like a def un, but instead of defining the value a call should produce, it defines how a call should be translated. For example, a macro to set its argument to nil might be defined as follows:

#+begin_src lisp
(defmacro nil! (x)
    (list 'setf x nil'))
#+end_src

This defines a new operator called /!nil/ which will take on argument. To test a macro we look at its expansion. The function macroexpand-1 takes a macro call and generates its expansion:

#+begin_src lisp
(macroexpand-1 '(nil! x))
(SETF X NIL)
#+end_src

** Backquote

The backquote read-macro makes it possible to build lists from templates. Backquote is used extensively in macro definitions. The advantage of backquote is that within a backquoted expression you can use a , and ,@ to turn evaluation back on.

* CLOS

The Common Lisp Object System or CLOS, is a set of operators for doing object-oriented programming.

** Object-Oriented Programming

Object-oriented programming means a change in the way programs are organized. It breaks up traditional programs in such a way that, instead of having a single program that operates on an inert mass of data, the data itself is told how to behave and the program is implicit in the interacitons of these new data "objects".

In the object-oriented model, our program gets broken up int oseveral distinct methods, each one intended for certain kinds of arguments. Together with this way of breaking up functions int odistinct methods, object-oriented progrmaming implies inheritance - both of slots and methods. In practical terms, object-oriented programming means organizing a program in terms of methods, classes, instances and inheritance. One of the claims of the object-oriented approach is that it makes programs easier to change.

** Classes and Instances

We can define a class using *defclass*:

#+begin_src lisp
(defclass circle ()
   (radius center))
#+end_src

This definition says that instances of the circle class will have two slots, named radius and center respectively. To make instances of this class, we can call the general ~make-instance~ with the class as the first argument:

#+begin_src lisp
> (setf c (make-instance 'circle))
#<Circle #XC27496>
#+end_src

To set the slots:

~(setf (slot-value c 'radius) 1)~

The values of uninitialized slots are undefined.

** Slot Properties

The third argument to ~defclass~ must be a list of slot definitions. In the general case a slot definition can be a list of a name followed by one or more properties, which are specified like keyword arguments. By defining an ~:accessor~ for a slot, we implicitly define a function that refers to the slot.

#+begin_src lisp :tangle yes
(defclass circle ()
 ((radius :accessor circle-radius)
  (center :accessor circle-center)))
#+end_src

Then we will be able to refer to the slots as circle-radius and circle-center respectively. By specifying a :reader instead of an ~:accessor~, we could get just the first half of this behavior, or just the second. To specify a default value for a slot, we have to give an ~:initform~ argument. if we want to be able ot initialize the slot in the call to make-instance we define a parameter name as an ~:initarg~. We can specify that some slots are to be shared. We do this by delcaring the slot to have :allocation :class (the alternative would be :allocation :instance, but it's the implicit default).

** Superclasses

The second argument to ~defclass~ is a list of ~superclasses~. A class inherits the union of the slots of its superclasses. So if we define the class ~screen-circle~ to be a subclass of both ~circle~ and ~graphic~,

#+begin_src lisp :tangle yes
(defclass graphic ()
 ((color :accessor graphic-color :initarg :color)
  (visible :accessor graphic-visible :initarg :visible
   :initform t)))

(defclass screen-circle (circle graphic)
 ())
#+end_src

* Structure

** Shared Structure

Lists can share conses in common. In the simplest case, one list might be part of another. After

#+begin_src lisp :tangle yes
> (setf part (list 'b 'c))
(B C)
> (setf whole (cons 'a part'))
(A B C)
#+end_src

the first cons is part of the second. In situations like this, we say that the two lists share structure. The predicate ~tailp~ detects this situation. It takes two lists and returns true if the first would be encountered on traversing the second:

#+begin_src lisp :tangle yes
> (tailp part whole)
T
#+end_src

** Modification

If two lists share structure, and we modify one, then we may inadvertently be modifying the other. In the previous section, we saw how to make one list a tail of another modifying shared structure can cause some very subtle bugs.

Lisp programmers learn to be aware of shared structure, and to suspect it immediately in certain kinds of errors. When a list mysteriously changes for no apparent reason, it is probably because you changed something else that shared structure with it. It is not the shared structure that's dangerous, but the changingo be on the safe side, simply avoid using s e t f (or related operators like pop, rplaca, etc.) on list structure, and you won't run into any problems.

** Example: Queues
