#+title: Power Management Nvidia Systemctl

The systemd configuration uses the following files, all of which are provided in /usr/share/doc/NVIDIA_GLX-1.0/samples:

/etc/systemd/system/nvidia-suspend.service

    A systemd service description file used to instruct the system manager to write suspend to the /proc/driver/nvidia/suspend interface immediately before accessing /sys/power/state to suspend the system.
/etc/systemd/system/nvidia-hibernate.service

    A systemd service description file used to instruct the system manager to write hibernate to the /proc/driver/nvidia/suspend interface immediately before accessing /sys/power/state to hibernate the system.
/etc/systemd/system/nvidia-resume.service

    A systemd service description file used to instruct the system manager to write resume to the /proc/driver/nvidia/suspend interface immediately after returning from a system sleep state.
/lib/systemd/system-sleep/nvidia

    A systemd-sleep script file used to instruct the system manager to write resume to the /proc/driver/nvidia/suspend interface immediately after an unsuccessful attempt to suspend or hibernate the system via the /proc/driver/nvidia/suspend interface.
/usr/bin/nvidia-sleep.sh

    A shell script used by the systemd service description files and the systemd-sleep file to interact with the /proc/driver/nvidia/suspend interface. The script also manages VT switching for the X server, which is currently needed by the NVIDIA X driver to support power management operations.

Each of these files needs to be installed to their intended target location as root, e.g.:

#+begin_src
    sudo install /usr/share/doc/NVIDIA_GLX-1.0/samples/systemd/nvidia-suspend.service /etc/systemd/system

    sudo install /usr/share/doc/NVIDIA_GLX-1.0/samples/systemd/nvidia-hibernate.service /etc/systemd/system

    sudo install /usr/share/doc/NVIDIA_GLX-1.0/samples/systemd/nvidia-resume.service /etc/systemd/system

    sudo install /usr/share/doc/NVIDIA_GLX-1.0/samples/systemd/nvidia /lib/systemd/system-sleep

    sudo install /usr/share/doc/NVIDIA_GLX-1.0/samples/systemd/nvidia-sleep.sh /usr/bin
#+end_src

The NVIDIA systemd services then need to be enabled:

    #+begin_src
    sudo systemctl enable nvidia-suspend.service

    sudo systemctl enable nvidia-hibernate.service

    sudo systemctl enable nvidia-resume.service
    #+end_src
