The expressive power of the class of [[Compound Procedures|procedures]]
that we can define at this point is very limited, because we have no way
to make tests and to perform different operations depending on the
result of a test. For instance, we cannot define a procedure that
computes the absolute value of a number by testing whether the number is
positive, negative, or zero and taking different actions in the
different cases according to the rule

\(\frac{1}{1 \cdot 3}+\frac{1}{5 \cdot 7}+\frac{1}{9 \cdot 11}+...\)

This construct is called a /case analysis/, and there is a special form
in [[Programming Algorithms in Lisp|Lisp]] for notating such a case
analysis. It is called cond (which stands for "conditional"), and it is
used as follows:

#+begin_src lisp
(define (abs x)  
  (cond ((> x 0) x)  
        ((= x 0) 0)  
        ((< x 0) (- x))))
#+end_src

The general form of a conditional expression is

\[
\begin{aligned}
(cond (<p_1> <e_1>) \\  
      (<p_2> <e_2>) \\
      ⋮  \\
      (<p_n> <e_n>)) \\
\end{aligned}
\]

consisting of the symbol cond followed by parenthesized pairs of
expressions (</p/> </e/>) called /clauses/. The first expression in each
pair is a /predicate/ -- that is, an expression whose value is
interpreted as either true or false.

Conditional expressions are evaluated as follows. The predicate </p1/>
is evaluated first. If its value is false, then </p2/> is evaluated. If
</p2/>'s value is also false, then </p3/> is evaluated. This process
continues until a predicate is found whose value is true, in which case
the interpreter returns the value of the corresponding /consequent
expression/ </e/> of the clause as the value of the conditional
expression. If none of the </p/>'s is found to be true, the value of
the cond is undefined.

In addition to primitive predicates such as <, =, and >, there are
logical composition operations, which enable us to construct compound
predicates. The three most frequently used are these:

- \((and <e_1> ... <e_n>)\)

The interpreter evaluates the expressions </e/> one at a time, in
left-to-right order. If any </e/> evaluates to false, the value of
the and expression is false, and the rest of the </e/>'s are not
evaluated. If all </e/>'s evaluate to true values, the value of
the and expression is the value of the last one.

- \((or <e_1> ... <e_n>)\)

The interpreter evaluates the expressions </e/> one at a time, in
left-to-right order. If any </e/> evaluates to a true value, that value
is returned as the value of the or expression, and the rest of the
</e/>'s are not evaluated. If all </e/>'s evaluate to false, the value
of the or expression is false.

- \((not <e>)\)

The value of a not expression is true when the expression </e/>
evaluates to false, and false otherwise.
