BTRFS is a modern copy on write (COW) filesystem for Linux aimed at
implementing advanced features while also focusing on fault tolerance,
repair and easy administration.

** Subvolumes
:PROPERTIES:
:CUSTOM_ID: subvolumes
:END:
"A btrfs subvolume is not a block device (and cannot be treated as one)
instead, a btrfs subvolume can be thought of as a POSIX file namespace.
This namespace can be accessed via the top-level subvolume of the
filesystem, or it can be mounted in its own right." Each Btrfs file
system has a top-level subvolume with ID 5. It can be mounted as =/= (by
default), or another subvolume can
be [[https://wiki.archlinux.org/title/Btrfs#Mounting_subvolumes][mounted]] instead.
Subvolumes can be moved around in the filesystem and are rather
identified by their id than their path.

To create a subvolume, the btrfs filesystem must be mounted. The
subvolume's name is set using the last argument.

#+begin_src sh
# btrfs subvolume create _/path/to/subvolume_
#+end_src

To see a list of current subvolumes and their ids under =_path_=:

#+begin_src sh
# btrfs subvolume list -p _path_
#+end_src

To delete a subvolume:

#+begin_src sh
# btrfs subvolume delete _/path/to/subvolume_
#+end_src

*** Mounting Subvolumes
:PROPERTIES:
:CUSTOM_ID: mounting-subvolumes
:END:
Subvolumes can be mounted like file system partitions using
the =subvol=_/path/to/subvolume_= or =subvolid=_objectid_= mount flags.
For example, you could have a subvolume named =subvol_root= and mount it
as =/=. One can mimic traditional file system partitions by creating
various subvolumes under the top level of the file system and then
mounting them at the appropriate mount points.

** Snapshots
:PROPERTIES:
:CUSTOM_ID: snapshots
:END:
"A snapshot is simply a subvolume that shares its data (and metadata)
with some other subvolume, using btrfs's COW capabilities."

To create a snapshot:

#+begin_src sh
# btrfs subvolume snapshot _source_ [_dest_/]_name_
#+end_src

The Btrfs filesystem supports 2 types of snapshots.

1. *Writable snapshots:* If you take a writable snapshot, you can modify
   that snapshot's files/directories later. This is the default snapshot
   type of the Btrfs filesystem.
2. *Read-only snapshots:* If you take a read-only snapshot, you can't
   modify that snapshot's files/directories later.
