* Hash Tables

A *hash table* generalizes the simpler notion of an ordinary array. Directly addressing int oan ordinary array makes effective use of our ability to examine an arbitrary position in an array in $\theta(1)$ time.

When the number of keys actually stored is small relative to the total number of possible kes, hash tables become an effective alternative to directly addressing an array, since a hash table typically uses an array of size proportional to the number of keys actually stored.

** Direct-address tables

*Direct addressing* is a simple technique that works well when the universe $U$ of keys is reasonably small. To represent the dynamic set, we use an array or direct-address table, denoted by ~T[0..m-1]~, in which each position or slot corresponds to a key in the universe $U$

*DIRECT-ADDRESS-SEARCH (T,k)*
1 ~return T[k]~

*DIRECT-ADDRESS-INSERT (T,x)*
1 ~T[x.key] = x~

*DIRECT-ADDRESS-DELETE (T,x)*
1 ~T T[x.key] = NIL~

Each of these operations takes only $\theta(1)$ time. The downside of direct addressing is obvious: if the universe U is large, storing a table $T$ of size $|U|$ may be impractical, or even impossible, given the memory available on a typical computer.

Two keys may hash to the same slot. We call this situation a *collision*. The ideal solution would be to avoid collisions altogether, but it's impossible. Thus, while the idea of a well-designed, "random" looking hash function can minimize the number of collisions, we still need a method for resolving the collisions that do occur.

** Collision resolution by chaining

In *chaining*, we place the elements that hash to the same slot into the same linked list. Slot $j$ contains a pointer to the head of the list of all stored elements that hash to $j$; if there are no such elements, slot j contains ~NIL~. The dictionary operations on a hash table T are easy to implement when collisions are resolved by chaining:

*CHAINED-HASH-INSERT (T,x)*
1   ~insert x at the head of list T[h(x.key)]~

*CHAINED-HASH-SEARCH (T,k)*
1   ~search for an element with key k in list T[h(k)]~

*CHAINED-HASH-DELETE (T,x)*
1   ~delete x from the list T[h(x.key)]~

The worst-case running time for insertion is $\theta(1)$. The insertion procedure is fast in part because it assumes that the element x being inserted is not already present in the table; if necessary, we can check this assumption (at additional cost) by searching for an element whose key is ~x.key~ before we insert.
For searching, the worst-case running time is proportional to the length of the list.
