#+title: Process Creation

How does the OS get a program up and running? How does process creation actually work? The first thing that the OS must do to run a program is to load its code and any static data into memory, into the address space of the process. Programs initially reside on disk (or, in some modern systems, flash-based SSDs) in some kind of executable format; thus, the process of loading a program and static data into memory requires the OS to read those bytes from disk and place them in memory somewhere. In early operating systems, the loading process is done eagerly all at once before running the program; modern OSes perform the process lazily, by loading pieces of code or data only as they are needeed during program execution, which involves other topics such as paging and swapping.

Once the code and static data are loaded into memory, there are a few other things the OS needs to do before running the process. Some memory must be allocated for the program's run-time stack (or just stack). As you should likely already know, C programs use the stack for local variables, function parameters and return addresses; the OS allocates this memory and gives it to the process. The OS may also create some initial memory for the program's heap. In C programs, the heap is used for explicitly requested dynamically allocated data; programs request such space by calling ~malloc()~ and free it by calling ~free()~. The heap is needed for data structures such as linked lists, hash tables, tress and others. The heap will be small at first; as the program runs and requests more memory via the ~malloc()~ library API, the OS may get invovled and allocate more memory to the process to help satisfy such calls. The OS will also do some other initialization tasks. In UNIX systems, each process by default has three open file descriptors, for standard input, output and error

By jumping to the ~main()~ routine, the OS transfers control of the CPU to the newly-created process, and thus the program begins its execution.
