#+title: Process

A process is, in simple terms, a running proram. The program itself is a lifeless thing, it is the oeprating system that takes these bytes and gets them running, transforming the program into something useful. A typical system may be seemingly running tens or even hunderds of processes at the same time. Although there are only a few physical CPUs available, how can the OS provide the illusion of a nearly endless supply of said CPUs? The operating system creates this illusion by virtualizing the CPU, by running one process, then stopping it and running another.
This basic technique, known as time sharing of the CPU, alows users to run as many concurrent processes as they would like; the potential cost is performance. The natural counterpart of time sharing is space sharing, where a resource is divided in space among those who wish to use it. For example, disk space is naturally a space-shared resource, as once a block is assigned to a file, it is not likely to be assigned to another file until the user deletes it.
On top of these mechanisms resides some of the intelligence in the OS, in the form of policies, algorithms for making some kind of decision within the OS.
