#+title: Stacks And Queues

*Stacks and queues* are *dynamic sets* in which the element of the set by the *DELETE* operation is prespecified. In a stack, the element deleted from the set is the one most recently inserted: the stack implements a last-in, first-out, or *LIFO* policy. Similarly, in a queue, the element deleted is always the one that has been in the set for the longest time: the queue implements a first-in, first-out or *FIFO* policy.

** Stacks

The *INSERT* operation on a stack is often called *PUSH*, and the *DELETE* operation is often called *POP*.
We can implement a stack of at most n elements with an array ~S[1..n]~. The array has an attribute ~S.top~ that indexes the most recently inserted element. The stack consists of elements ~S[1..S.top]~, where ~S[1]~ is the element at the bottom of the stack and ~S[S.top]~ is the element at the top.
When ~S.top = 0~, the stack contains no elements and is empty. We can test whether the stack i empty by query operation ~STACK-EMPTY~. If we attempt to pop an empty stack we say the stack *underflows*, which is normally an error. If ~S.top~ exceeds n, the stack *overflows*.

** Queues

We call the *INSERT* operation on a queue *ENQUEUE* and we call the *DELETE* operation *DEQUEUE*; like the stack operation *POP*, *DEQUEUE* takes no element argument.
The *FIFO* property of a queue causes it to operate like a line of customers waiting to pay a cashier. The queue has a *head* and a *tail*. When an element in enqueued, it takes its place at the tail of the queue, just as a newly arriving customer takes a place at the end of the line. The element dequeued is always the one at the head of the queue.
We can implement a queue of at most $n-1$ elements using an array ~Q[1..n]~. The queue has an attribute ~Q.head~ that indexes or points to its head. The attribute ~Q.tail~ indexes the next location at which a newly arriving element will be inserted into the queue. The elements in the queue reside in locations ~Q.head, Q.head +1,..., Q.tail -1~, where we "wrap around" in the sense that location 1 immediately follows location n in a circular order. Whe ~Q.head = Q.tail~ the queue is *empty*.
